TDI.AdActivity/AdActivity.Mvc/Models/ErrorViewModel.cs
using System;

namespace AdActivity.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TDI.AdActivity/AdActivity.Mvc/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AdActivity.Mvc.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TDI.AdActivity/AdActivity.Mvc/Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdActivity.Application.Interfaces;
using AdActivity.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AdActivity.Mvc.Controllers
{
    public class CampaignController : Controller
    {
        private ICampaignService _campaignService;

        public CampaignController(ICampaignService campaignService)
        {
            _campaignService = campaignService;
        }

        public IActionResult Index()
        {
            return View(_campaignService.GetCampaigns());
        }

        [HttpGet]
        public IActionResult CreateCampaign()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateCampaign(CampaignViewModel campaignViewModel)
        {
            _campaignService.Create(campaignViewModel);
            return RedirectToAction("Index");
        }

        public PartialViewResult AdminPrivilages()
        {
            return PartialView("_adminPrivilege");
        }
    }
}

TDI.AdActivity/AdActivity.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AdActivity.Mvc.Models;

namespace AdActivity.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TDI.AdActivity/AdActivity.Mvc/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin Page";
}

<div class="content animate-panel">
    <partial name="~/Views/Shared/_adminPrivilege.cshtml" />
</div>

TDI.AdActivity/AdActivity.Mvc/Views/Campaign/CreateCampaign.cshtml
@model CampaignViewModel

@{
    ViewBag.Title = "Create Campaign";
}

<partial name="~/Views/Shared/_subHeader.cshtml" />

<div class="content animate-panel">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        @*<a class="closebox"><i class="fa fa-times"></i></a>*@
                    </div>
                    Create Campaign
                </div>
                <div class="panel-body">
                    <form asp-controller="Campaign" asp-action="CreateCampaign" method="post" class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-2 control-label" asp-for="CAMName">Campaign Name</label>
                            <div class="col-sm-10">
                                <input asp-for="CAMName" placeholder="Campaign Name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" asp-for="CAMDesc">Campaign Description</label>
                            <div class="col-sm-10">
                                <textarea asp-for="CAMDesc" class="form-control" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" asp-for="BRNId">Select Brand</label>
                            <div class="col-sm-10">
                                <select asp-for="BRNId" class="form-control m-b">
                                    <option value="1">FDAF</option>
                                    <option value="2">LMDA</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="FundingTypeId" class="col-sm-2 control-label">Select Funding Type</label>
                            <div class="col-sm-10">
                                <select asp-for="FundingTypeId" class="form-control m-b">
                                    <option value="1">Unknown</option>
                                    <option value="2">Ford Funded</option>
                                    <option value="3">Non Ford Funded</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="ActiveStatus" class="col-sm-2 control-label">Status</label>
                            <div class="col-sm-10">
                                <div class="radio-inline">
                                    <label>
                                        <input asp-for="ActiveStatus" value="A" class="i-checks" type="radio" checked> Active
                                    </label>
                                </div>
                                <div class="radio-inline">
                                    <label>
                                        <input asp-for="ActiveStatus" value="I" class="i-checks" type="radio"> Inactive
                                    </label>
                                </div>
                                <div class="radio-inline">
                                    <label>
                                        <input asp-for="ActiveStatus" value="O" class="i-checks" type="radio"> Obselete
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="IsPlaceholder" class="col-sm-2 control-label">Is Placeholder?</label>
                            <div class="col-sm-10">
                                <div class="checkbox-inline">
                                    <input asp-for="IsPlaceholder" type="checkbox" class="i-checks">
                                </div>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-8 col-sm-offset-2">
                                <button class="btn btn-default" type="button">Cancel</button>
                                <button class="btn btn-primary" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

TDI.AdActivity/AdActivity.Mvc/Views/Campaign/Index.cshtml
@model IEnumerable<CampaignViewModel>

@{
    ViewBag.Title = "Campaign List";
}
<partial name="~/Views/Shared/_subHeader.cshtml" />

<div class="content animate-panel">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel hblue">
                <div class="panel-heading hbuilt">
                    <div class="pull-right">
                        <a asp-controller="Campaign" asp-action="CreateCampaign" class="btn btn-outline btn-success btn-xs"><i class="pe-7s-plus"></i> Add New Campaign</a>
                        @*<a class="btn btn-default btn-xs">Action 2</a>*@
                    </div>
                    Campaigns
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table cellpadding="1" cellspacing="1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Campaign Name</th>
                                    <th>Description</th>
                                    <th>Brand</th>
                                    <th>Funding Type</th>
                                    <th>Status</th>
                                    <th>Is Placeholder</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var campaign in Model)
                                {
                                    <tr>
                                        <td>@campaign.CAMName</td>
                                        <td>@campaign.CAMDesc</td>
                                        <td>@campaign.Brand.BRNType</td>
                                        <td>@campaign.FundingType.Description</td>
                                        <td>@(campaign.ActiveStatus=="A"?"Active":"Inactive")</td>
                                        <td>@(campaign.IsPlaceholder?"Yes":"No")</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="panel-footer">
                    Campaigns - @Model.Count() rows
                </div>
            </div>
        </div>
    </div>
</div>

TDI.AdActivity/AdActivity.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="content animate-panel">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="display-4">Welcome to Ad-Activity</h1>
        </div>
    </div>
</div>

TDI.AdActivity/AdActivity.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<!-- Mirrored from webapplayers.com/homer_admin-v1.9/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 21 Apr 2016 06:12:31 GMT -->
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Page title -->
    <title>@ViewBag.Title</title>

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <!--<link rel="shortcut icon" type="image/ico" href="favicon.ico" />-->
    <!-- Vendor styles -->
    <link href="~/lib/fontawesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/metisMenu/dist/metisMenu.css" rel="stylesheet" />
    <link href="~/lib/animate.css/animate.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

    <!-- App styles -->
    <link href="~/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css" rel="stylesheet" />
    <link href="~/fonts/pe-icon-7-stroke/css/helper.css" rel="stylesheet" />
    <link href="~/styles/style.css" rel="stylesheet" />
</head>
<body class="fixed-navbar fixed-sidebar">

    <!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header -->
    <div id="header">
        <div class="color-line">
        </div>
        <div id="logo" class="light-version">
            <span>
                Ad-Activity
            </span>
        </div>
        <nav role="navigation">
            <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
            <div class="small-logo">
                <span class="text-primary">Ad-Activity</span>
            </div>
            <form role="search" class="navbar-form-custom" method="post" action="#">
                <div class="form-group">
                    <input type="text" placeholder="Search something special" class="form-control" name="search">
                </div>
            </form>
            <div class="mobile-menu">
                <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
                    <i class="fa fa-chevron-down"></i>
                </button>
                <div class="collapse mobile-navbar" id="mobile-collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a class="" href="#">Login</a>
                        </li>
                        <li>
                            <a class="" href="#">Logout</a>
                        </li>
                        <li>
                            <a class="" href="#">Profile</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="navbar-right">
                <ul class="nav navbar-nav no-borders">
                    <li>
                        <a href="#" id="sidebar" class="right-sidebar-toggle">
                            <i class="pe-7s-users"></i>
                            <span class="label" style="font-size:50%;vertical-align:middle;color:#6a6c6f; padding:0;">Change Committee</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Admin" asp-action="Index" id="sidebar" class="right-sidebar-toggle">
                            <i class="pe-7s-config"></i>
                            <span class="label" style="font-size:50%;vertical-align:middle;color:#6a6c6f; padding:0;">Administration</span>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle label-menu-corner" href="#" data-toggle="dropdown">
                            <i class="pe-7s-mail"></i>
                            <span class="label label-success">4</span>
                        </a>
                        <ul class="dropdown-menu hdropdown animated flipInX">
                            <div class="title">
                                You have 4 new messages
                            </div>
                            <li>
                                <a>
                                    Lorem Ipsum is simply dummy.
                                </a>
                            </li>
                            <li>
                                <a>
                                    Lorem Ipsum is simply dummy.
                                </a>
                            </li>
                            <li>
                                <a>
                                    Lorem Ipsum is simply dummy.
                                </a>
                            </li>
                            <li>
                                <a>
                                    Lorem Ipsum is simply dummy.
                                </a>
                            </li>
                            <li class="summary"><a href="#">See All Messages</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                            <i class="pe-7s-upload pe-rotate-90"></i>
                        </a>
                        <ul class="dropdown-menu animated flipInX m-t-xs">
                            <li><a href="#">Change Password</a></li>
                            @*<li class="divider"></li>*@
                            <li><a href="#">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <!-- Navigation -->
    <aside id="menu">
        <div id="navigation">
            <div class="profile-picture">
                <a href="#">
                    <img src="~/images/profile1.png" width="76" height="76" class="img-circle m-b" alt="logo">
                </a>

                <div class="stats-label text-color">
                    <span class="font-extra-bold font-uppercase">Santhosh Dwarakanath</span>
                </div>
            </div>

            <ul class="nav" id="side-menu">
                <li class="active">
                    <a href="#"> <span class="nav-label">Dashboard</span></a>
                </li>
                <li>
                    <a href="#"> <span class="nav-label">Activity</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="#">View/Edit Activity</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"> <span class="nav-label">Offers</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="#">Enter/Edit Offers</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"> <span class="nav-label">Creatives</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="#">View Creative Id</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><span class="nav-label">Reports</span></a>
                </li>
            </ul>
        </div>
    </aside>

    <!-- Main Wrapper -->
    <div id="wrapper">

        @RenderBody()

        <!-- Footer-->
        <footer class="footer">
            <span class="pull-right">
                Example text
            </span>
            Company 2020
        </footer>

    </div>

    <!-- Vendor scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/slimScroll/jquery.slimscroll.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-flot/jquery.flot.js"></script>
    <script src="~/lib/jquery-flot/jquery.flot.resize.js"></script>
    <script src="~/lib/jquery-flot/jquery.flot.pie.js"></script>
    <script src="~/lib/flot.curvedlines/curvedLines.js"></script>
    <script src="~/lib/jquery.flot.spline/index.js"></script>
    <script src="~/lib/metisMenu/dist/metisMenu.min.js"></script>
    <script src="~/lib/iCheck/icheck.min.js"></script>
    <script src="~/lib/peity/jquery.peity.min.js"></script>
    <script src="~/lib/sparkline/index.js"></script>

    <!-- App scripts -->
    <script src="~/js/homer.js"></script>
    <script src="~/js/charts.js"></script>

    @RenderSection("Scripts", required: false)
</body>

<!-- Mirrored from webapplayers.com/homer_admin-v1.9/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 21 Apr 2016 06:13:05 GMT -->
</html>

TDI.AdActivity/AdActivity.Mvc/Views/Shared/_adminPrivilege.cshtml
    <div class="row">
        <div class="col-md-3">
            <div class="hpanel">
                <div class="panel-body">
                    <div class="text-center">
                        <h2 class="m-b-xs">User Management</h2>
                        <p class="font-bold text-success">Add, Edit or Delete Users</p>
                        <div class="m">
                            <i class="pe-7s-add-user fa-5x"></i>
                        </div>
                        <p class="small">
                            Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                        <button class="btn btn-success btn-sm">Explore</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="hpanel">
                <div class="panel-body">
                    <div class="text-center">
                        <h2 class="m-b-xs">Reports Management</h2>
                        <p class="font-bold text-info">Lorem ipsum</p>
                        <div class="m">
                            <i class="pe-7s-look fa-5x"></i>
                        </div>
                        <p class="small">
                            Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                        <button class="btn btn-info btn-sm">Explore</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="hpanel">
                <div class="panel-body">
                    <div class="text-center">
                        <h2 class="m-b-xs">Campaign Management</h2>
                        <p class="font-bold text-warning">Add, Edit or Delete Campaigns</p>
                        <div class="m">
                            <i class="pe-7s-cup fa-5x"></i>
                        </div>
                        <p class="small">
                            Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                        <a class="btn btn-success btn-sm" asp-controller="Campaign"
                           asp-action="Index">Explore</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="hpanel">
                <div class="panel-body">
                    <div class="text-center">
                        <h2 class="m-b-xs">Carline Management</h2>
                        <p class="font-bold text-danger">Add, Edit or Delete Carlines</p>
                        <div class="m">
                            <i class="fa fa-car fa-5x"></i>
                        </div>
                        <p class="small">
                            Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                        <button class="btn btn-danger btn-sm">Explore</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

TDI.AdActivity/AdActivity.Mvc/Views/Shared/_subHeader.cshtml
    <div class="small-header transition animated fadeIn">
        <div class="hpanel">
            <div class="panel-body">
                <div id="hbreadcrumb" class="pull-right">
                    <ol class="hbreadcrumb breadcrumb">
                        <li><a href="#">Dashboard</a></li>
                        <li>
                            <span>Administration</span>
                        </li>
                        <li>
                            <span>Campaign</span>
                        </li>
                        <li class="active">
                            <span>Create Campaign </span>
                        </li>
                    </ol>
                </div>
                <h2 class="font-light m-b-xs">
                    Campaign Management
                </h2>
                <small>View, Add or Edit Campaigns</small>
            </div>
        </div>
    </div>